services:
  - docker

# Pre-testing installs
install: 
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_install: 
  - echo "no tests"

script: 
  - docker --version
  - docker build -t udagram-reverse-proxy . # Build
  - docker tag udagram-reverse-proxy qmnguyenw/udagram-reverse-proxy:v1 # Tagging

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success: 
  # Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin # Login
  - docker push qmnguyenw/udagram-reverse-proxy:v1 # Push

